// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDUP8G8V2TIVphL8-JggAjXZtlnrK1dlc',
    appId: '1:626836008655:web:96b1b2e07c513d0f6e11ba',
    messagingSenderId: '626836008655',
    projectId: 'i-am-talking',
    authDomain: 'i-am-talking.firebaseapp.com',
    storageBucket: 'i-am-talking.appspot.com',
    measurementId: 'G-2KYF8GR88T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpwM2czstd28-VNAlN9xoLYbFnVYH2GY0',
    appId: '1:626836008655:android:99a22ab01d884fa96e11ba',
    messagingSenderId: '626836008655',
    projectId: 'i-am-talking',
    storageBucket: 'i-am-talking.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBADZXxeOMmsAIXVsS4800jMicwrHo72Uo',
    appId: '1:626836008655:ios:aac8b477e583c44f6e11ba',
    messagingSenderId: '626836008655',
    projectId: 'i-am-talking',
    storageBucket: 'i-am-talking.appspot.com',
    androidClientId: '626836008655-an3orusibefjp48c1iu3jbhp58kh056f.apps.googleusercontent.com',
    iosClientId: '626836008655-7pgpeqh1ddhr0pm33ig13p0dh5h9e4rk.apps.googleusercontent.com',
    iosBundleId: 'com.example.iamtalking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDUP8G8V2TIVphL8-JggAjXZtlnrK1dlc',
    appId: '1:626836008655:web:1e123e380ecadafc6e11ba',
    messagingSenderId: '626836008655',
    projectId: 'i-am-talking',
    authDomain: 'i-am-talking.firebaseapp.com',
    storageBucket: 'i-am-talking.appspot.com',
    measurementId: 'G-G3WW1YR87K',
  );

}